server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Evita que los archivos estáticos devuelvan index.html si no existen,
    # y los cachea correctamente.
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
        try_files $uri =404;
        expires max;
        log_not_found off;
    }
}
